name: ci

on:
  pull_request:
    branches:
    - master

jobs:

  pull:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [e2e]
    steps:
    - name: Set up Go 1.13.4
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/cofyc/ginkgo-testing
    - name: make ${{ matrix.target }}
      run: |
        export GOPATH=/home/runner/work/ginkgo-testing/go
        make $target
      env:
        target: ${{ matrix.target }}
